### ISSUE TITLE
サンプルを用意してsubscriberのいないjoint_state_publisherを無効にする

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/crane_x7_ros#32]
https://github.com/rt-net/crane_x7_ros/pull/31#issuecomment-432926833

**Comment by Tiryoh** [comment]
ここの「サンプル」はrt-net/crane_x7_rosを使うためのサンプルです。
関連: https://github.com/rt-net/crane_x7_ros/pull/31#issuecomment-432926340, https://github.com/rt-net/crane_x7_ros/pull/31#issuecomment-432926833
すでに https://github.com/rt-net/crane_x7_ros/tree/master/crane_x7_examples に `/joint_states` をサブスクライブするサンプルがあるので、`joint_state_publisher` を無効にして問題ないと思われます。

**Comment by ShotaAk** [comment]
`/joint_state` をパブリッシュしないように変更したら、サンプル(teaching_example)が正常に動きませんでした。

```bash
[Teaching Mode] [Next Pose:0 of 0]
[q]: Quit, [m]: switch to action Mode, [s]: Save, [d]: Delete
Keyboard input >>>
s 
Save joint values
[ INFO] [1557400500.583543964]: Didn't received robot state (joint angles) with recent timestamp within 1 seconds.
Check clock synchronization if your are running ROS across multiple machines!
[ERROR] [1557400500.583623944]: Failed to fetch current robot state
[ INFO] [1557400501.583820926]: Didn't received robot state (joint angles) with recent timestamp within 1 seconds.
Check clock synchronization if your are running ROS across multiple machines!
[ERROR] [1557400501.583888306]: Failed to fetch current robot state
Error setting joint target. Is the target within bounds?

```

おそらく、MoveGroupCommanderが、`/crane_x7/joint_states`ではなく、`/joint_states`を参照しているからだと思います。

もしかしたら、NameSpaceを上手に修正すれば、`/crane_x7/joint_states`を参照できるかもしれません。
https://github.com/ros-planning/moveit_tutorials/issues/303

**Comment by ShotaAk** [comment]
参考までに、X7と同じように、`/joint_states`と、`/***/joint_states`の両方をパブリッシュしている人もいるみたいです。

https://github.com/start-jsk/denso/issues/97

**Comment by ShotaAk** [comment]
`/joint_states`はMoveIt (move_group)がサブスクライブします。

これはサンプル（例：`rosrun crane_x7_examples crane_x7_pick_and_place_demo.py`）を実行した際に、確認できます。

```sh
rostopic info /joint_states
Type: sensor_msgs/JointState

Publishers: 
 * /joint_state_publisher (http://192.168.11.110:40707/)

Subscribers: 
 * /moveit_python_wrappers_1633595770062936605 (http://192.168.11.110:42929/)
```

トピックのremapやネームスペース等を工夫すれば、`/joint_states`を吐き出す`/joint_state_publisher`を取り除けるかもしれませんが、修正に伴う検証範囲が広いため、現時点では対応しません。

このIssueはcloseします。
