### ISSUE TITLE
ハードウェア情報が古い

### ISSUE THREAD

**Issue by nomumuRT** [rt-net/crane_x7_ros#44]
制限角度や重量、重心位置などのハードウェア情報が古いので最新データに更新した方が良い。

**Comment by ShotaAk** [comment]
今後、X7のハードウェアが更新されることを想定して、
roslaunch時に参照するハードウェア情報を切り替えれるようにする。

**Comment by ShotaAk** [comment]
ハードウェア情報の切り替えは別issueで立てるので、本issueではハードウェア情報の更新のみを行う。

**Comment by ShotaAk** [comment]
#85 で修正済み。
