### ISSUE TITLE
ROS2への対応

### ISSUE THREAD

**Issue by Gandats** [rt-net/crane_x7_ros#89]
ROS2への対応予定はありますか。
多くの機械学習モデルがPython3系で公開されているので、ROS2で利用できるとありがたいです。

**Comment by nomumuRT** [comment]
アールティからROS向けに展開しています各製品について、ROS2への対応を検討中です。
CRANE-X7についてはMoveIt!を使用しているため、まずはMoveIt2の動向をWatchしている状況です。
MoveIt2は重要なパッケージですが、その他にもROS2の良さを生かすためには設計から見直す必要のある実装が多くあります。ROS2に対応しました！と自信を持ってリリースするまでには少なくない努力が求められると考えています。

Python3とROSの関係については色々と議論されています。現行のROSとPython3系のソフトウェアを接続する方法に関する情報も多くありますので、今すぐ必要ということであればそのような方法を選択するのが妥当かと思います。
ROS2への完全対応は時間がかかるので、例えば中間的にROS1とROS2を接続するbridgeパッケージを介してCRANE-X7をROS2から使用する方法をアナウンスできれば、良いステップかもしれませんね。

パッケージのアップデート作業に入る場合などIssueにて見えると思いますので、適宜チェックして頂ければと思います。

**Comment by Gandats** [comment]
承知しました。ありがとうございます。
