### ISSUE TITLE
Gazebo STLファイルのインポート

### ISSUE THREAD

**Issue by gakisin** [rt-net/crane_x7_ros#90]
CRANE-X7のGazebo上でメッシュをインポートしようと思います。Model EditorでSTLをインポートしましたが、[import]を押してからの後操作が分かりません。ご教授お願い致します。

**Comment by ShotaAk** [comment]
Gazeboの操作方法については公式チュートリアルを参照してください。
[Beginner: Model Editor](http://gazebosim.org/tutorials?tut=guided_b3)のページが参考になると思います。
CRANE-X7特有の問題があれば教えてください:thumbsup:

**Comment by gakisin** [comment]
回答ありがとうございます。
CRANE-X7は、今のところ問題ありません。
