### ISSUE TITLE
Gazebo　CRANE-X7の位置を変更方法

### ISSUE THREAD

**Issue by gakisin** [rt-net/crane_x7_ros#91]
GazeboでCRANE-X7の位置を変更する場合、どのファイルを変更すればいいですか。
宜しくお願い致します。

**Comment by ShotaAk** [comment]
launchファイルの引数を変更してみてください。

https://github.com/rt-net/crane_x7_ros/blob/1da902764b8b92f9826402ba78115a91f57d6157/crane_x7_gazebo/launch/crane_x7_with_table.launch#L40-L42

参考：
http://gazebosim.org/tutorials/?tut=ros_roslaunch

**Comment by gakisin** [comment]
-x -y -z でpositionのオフセットが出来る事がわかりました。
どうもありがとうございました。
